- name: Create and Upload UI-user-portal
  hosts: localhost
  tasks:
    - amazon.aws.s3_bucket:
      name: creates an s3 bucket
      state: present
      bucket: astcodersbank-user-portal
      mode: create
      permission: public-read

    - community.aws.s3_website:
      name: astcodersbank-user-portal
      state: present
      suffix: index.html

    - name: basic upload
      community.aws.s3_sync:
      bucket: tedder
      file_root: roles/s3/files/
      include: "*"
      permission: public-read
    